accent = "#686868"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#222222"
selection_foreground = "#ffffff"
selection_background = "#686868"

color0 = "#222222"
color1 = "#7c7c7c"
color2 = "#8b8b8b"
color3 = "#a0a0a0"
color4 = "#686868"
color5 = "#747474"
color6 = "#868686"
color7 = "#b9b9b9"
color8 = "#525252"
color9 = "#7c7c7c"
color10 = "#8b8b8b"
color11 = "#a0a0a0"
color12 = "#686868"
color13 = "#747474"
color14 = "#868686"
color15 = "#ffffff"
